export default [
    "Um animal que descobre um objeto mágico.",
      "Um grupo de amigos que encontra um mapa misterioso.",
      "Uma criança que sonha em viajar para o espaço.",
      "Uma cidade que guarda um segredo escondido.",
      "Um robô que aprende a sentir emoções.",
      "Um viajante que acorda em um mundo desconhecido.",
      "Um dragão que perdeu suas chamas.",
      "Um pirata que busca um tesouro diferente.",
      "Uma floresta onde as árvores falam.",
      "Uma escola de magia em pleno deserto.",
      "Uma princesa que deseja ser cavaleira.",
      "Um cientista que cria um portal acidentalmente.",
      "Um gato que sabe ler livros.",
      "Um castelo que muda de lugar toda noite.",
      "Um menino que encontra um par de asas.",
      "Um livro que escreve a própria história.",
      "Uma chave que abre qualquer porta.",
      "Um espelho que mostra futuros possíveis.",
      "Uma cidade feita inteiramente de doces.",
      "Uma criança que conversa com as estrelas.",
      "Um peixe que quer voar pelo céu.",
      "Uma mochila que guarda mundos inteiros.",
      "Um herói que tem medo da própria sombra.",
      "Um brinquedo que ganha vida de madrugada.",
      "Uma bicicleta que viaja no tempo.",
      "Um mago que esqueceu seus feitiços.",
      "Um reino onde os sonhos viram realidade.",
      "Uma ponte que só aparece sob a lua cheia.",
      "Um cachorro que guia exploradores perdidos.",
      "Uma criança que encontra uma cápsula do tempo.",
      "Um gigante que só quer um amigo.",
      "Uma ilha que muda de forma a cada maré.",
      "Um pintor que cria mundos com seus quadros.",
      "Uma estrela cadente que se torna humana.",
      "Uma árvore que concede desejos secretos.",
      "Um lago que mostra memórias esquecidas.",
      "Uma criança que entende a linguagem dos pássaros.",
      "Um guarda-chuva que voa como balão.",
      "Uma porta escondida atrás de uma estante.",
      "Um robô que sonha em ser poeta.",
      "Um planeta onde todos falam em música.",
      "Uma biblioteca que só abre à meia-noite.",
      "Um detetive que investiga sonhos roubados.",
      "Uma fada que perdeu suas asas.",
      "Um relógio que controla o tempo.",
      "Um reino de gelo eterno que guarda calor secreto.",
      "Uma criança que encontra uma carta misteriosa.",
      "Um vulcão que guarda um coração adormecido.",
      "Uma cor que nunca foi vista antes.",
      "Um amigo imaginário que ganha corpo real.",
      "Uma casa que se move sozinha.",
      "Uma criança que conversa com fantasmas bondosos.",
      "Um dragão que se esconde em forma de gato.",
      "Um circo que aparece apenas uma vez por século.",
      "Um viajante que encontra portas invisíveis.",
      "Uma caixa de música que muda o mundo.",
      "Uma sombra que vive sua própria vida.",
      "Um explorador que descobre um céu subterrâneo.",
      "Um rio que corre para cima.",
      "Uma criança que aprende magia com os ventos.",
      "Um navio fantasma que busca sua tripulação.",
      "Uma montanha que guarda segredos milenares.",
      "Um espelho que troca identidades.",
      "Um anel que sussurra histórias antigas.",
      "Uma criança que encontra uma fada presa em uma garrafa.",
      "Um dragão que coleciona memórias.",
      "Um jardim que floresce apenas com risadas.",
      "Uma estrada que leva a diferentes épocas.",
      "Um castelo invisível que só aparece para corajosos.",
      "Um mago que guarda enigmas em garrafas.",
      "Uma cidade escondida nas nuvens.",
      "Uma canção que abre portais.",
      "Uma criança que encontra botas mágicas.",
      "Um boneco de neve que nunca derrete.",
      "Uma porta que leva ao fundo do mar.",
      "Uma pedra que fala com quem a segura.",
      "Um meteoro que traz um novo amigo.",
      "Um teatro onde as peças viram realidade.",
      "Um cavalo que corre entre mundos.",
      "Uma criança que encontra uma pena mágica.",
      "Um fantasma que adora brincar.",
      "Um cristal que guarda sonhos.",
      "Uma criança que acorda em outro corpo.",
      "Uma escada que nunca termina.",
      "Um dragão guardião de livros.",
      "Uma criança que encontra um relógio quebrado que fala.",
      "Uma caixa que realiza apenas um desejo.",
      "Um planeta onde tudo é feito de cristal.",
      "Uma cidade onde nunca anoitece.",
      "Um amigo secreto que vive em cartas.",
      "Uma criança que descobre ser descendente de heróis."
]