import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontSize: 12,
    fontFamily: "Helvetica",
  },
  bingo: {
    justifyContent: "center",
    padding: 10,
    fontSize: 12,
    fontFamily: "Helvetica",
  },
  molde: {
    fontSize: 12,
    fontFamily: "Helvetica",
  },
  domino: {
    justifyContent: "center",
    marginTop: 5,
    padding: 0,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  hangman: {
    marginTop: 5,
    padding: 0,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  objectHunt: {
    justifyContent: "center",
    marginTop: 5,
    padding: 0,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  memoryGame: {
    marginTop: 5,
    padding: 0,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  storyGame: {
    marginTop: 5,
    padding: 0,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  wordSearch: {
    marginTop: 5,
    padding: 0,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  portugueseLetters: {
    justifyContent: "center",
    marginTop: 5,
    padding: 0,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  mapaMundi: {
    justifyContent: "center",
    marginTop: 5,
    padding: 0,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  desenharOrigem: {
    justifyContent: "center",
    marginTop: 5,
    padding: 0,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  apresentacao: {
    justifyContent: "center",
    marginTop: 5,
    padding: 0,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  minhaFamilia: {
    justifyContent: "center",
    marginTop: 5,
    padding: 0,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  h1: { fontSize: 16, marginBottom: 5 },
  h2: { fontSize: 14, marginTop: 12, marginBottom: 5 },
  p: { marginBottom: 5, lineHeight: 1.4 },
  list: { marginLeft: 12 },
  caption: {
    marginBottom: 5,
    lineHeight: 1.4,
    fontStyle: "italic",
    fontSize: 10,
    color: "#555",
  },
  captionLabel: {
    fontStyle: "italic",
    fontSize: 8,
    color: "#555",
    fontWeight: 700,
    marginBottom: 2,
  },
  image: { marginTop: 6, marginBottom: 6, alignSelf: "center" },
  //bingo styles
  bingoGrid: { marginTop: 12, gap: 0 },
  bingoRow: { flexDirection: "row" },
  bingoCell: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#000",
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  bingoText: { fontSize: 10, fontWeight: 500 },
  bingoCard: { marginBottom: 10 },
  //word search styles
  wordSearchGrid: { marginTop: 12, gap: 0 },
  wordSearchRow: { flexDirection: "row" },
  wordSearchCell: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#000",
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  wordSearchText: { fontSize: 10, fontWeight: 500 },
});